# Generated by Django 6.1.1 on 2026-09-14 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('free', '자유게시판'), ('exam_info', '시험정보 공유'), ('materials', '기출문제·자료실'), ('qna', '자격증 Q&A')], db_index=True, default='free', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('nickname', models.CharField(max_length=30)),
                ('password_hash', models.CharField(editable=False, max_length=128)),
                ('content', models.TextField()),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_notice', models.BooleanField(default=False, help_text='체크하면 목록 상단에 고정됩니다.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '게시글',
                'verbose_name_plural': '게시글',
                'ordering': ['-is_notice', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('password_hash', models.CharField(editable=False, max_length=128)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.post')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글',
                'ordering': ['created_at'],
            },
        ),
    ]
