"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from django.contrib.messages import constants as message_constants
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y0i9wg+(ix0fd4bkmx&d7-mm2az=)f68fb2oc&n&1q$_70*ym6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'analytics',
    'recommendations',
    'substitutes',
    'community',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'analytics'/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'sports_service_202607.sqlite3',
    },
    'community': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('COMMUNITY_DB_NAME', 'community_db'),
        'USER': os.environ.get('COMMUNITY_DB_USER', 'community_user'),
        'PASSWORD': os.environ.get('COMMUNITY_DB_PASSWORD', ''),
        'HOST': os.environ.get('COMMUNITY_DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('COMMUNITY_DB_PORT', '5432'),
    },
}

DATABASE_ROUTERS = [
    'main.db_routers.CommunityRouter',
]


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

# 부트스트랩은 alert-error가 아닌 alert-danger 클래스를 사용하므로 매핑해준다.
# 이 설정이 없으면 오류 메시지가 색이 입혀지지 않은 일반 텍스트로만 보인다.
MESSAGE_TAGS = {
    message_constants.ERROR: 'danger',
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

# 선행 슬래시가 없으면 /recommendations/ 같은 하위 URL에서
# /recommendations/static/... 으로 해석되어 정적 파일이 404가 된다.
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'analytics' / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 업로드 파일은 미리보기/검증 동안에만 임시 보관하고 저장 완료 후 삭제한다.
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024
DATA_UPLOAD_MAX_NUMBER_FIELDS = 2000

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 202607 원본 스냅샷의 월말. clean_program_data --reference-date로 덮어쓸 수 있다.
PROGRAM_CLEANUP_REFERENCE_DATE = '2026-07-31'

# 기관 상세 페이지 지도 표시에 사용하는 카카오맵 JavaScript 키.
# https://developers.kakao.com 에서 발급받은 후 사용 중인 도메인(localhost 포함)을
# 플랫폼 설정에 등록해야 지도가 표시된다. 환경 변수로 주입하는 것을 권장한다.
KAKAO_MAP_APP_KEY = os.environ.get('KAKAO_MAP_APP_KEY', '')


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
