# Generated by Django 6.1.1 on 2026-09-14 08:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0005_programcleanup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('phone_masked', models.CharField(max_length=20)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '전화번호 신원',
                'verbose_name_plural': '전화번호 신원',
            },
        ),
        migrations.CreateModel(
            name='CenterContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('phone_masked', models.CharField(max_length=20)),
                ('institution_name', models.CharField(max_length=200)),
                ('business_reg_no', models.CharField(blank=True, max_length=20)),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitute_contacts', to='app.institution')),
            ],
            options={
                'verbose_name': '센터 담당자',
                'verbose_name_plural': '센터 담당자',
            },
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('region', models.CharField(blank=True, max_length=100)),
                ('normalized_region', models.CharField(blank=True, db_index=True, max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('required_certifications', models.JSONField(blank=True, default=list)),
                ('pay_amount', models.PositiveIntegerField()),
                ('pay_unit', models.CharField(choices=[('session', '회당'), ('hour', '시간당')], default='hour', max_length=10)),
                ('headcount', models.PositiveSmallIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('recruiting', '모집중'), ('closed', '마감'), ('completed', '완료')], db_index=True, default='recruiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postings', to='substitutes.centercontact')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substitute_postings', to='app.canonicalsport')),
            ],
            options={
                'verbose_name': '대타 공고',
                'verbose_name_plural': '대타 공고',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_masked', models.CharField(max_length=20)),
                ('certification_verified', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('phone_identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='substitutes.phoneidentity')),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='substitutes.posting')),
            ],
            options={
                'verbose_name': '신청',
                'verbose_name_plural': '신청',
                'ordering': ['-applied_at'],
                'constraints': [models.UniqueConstraint(fields=('posting', 'phone_identity'), name='unique_posting_application')],
            },
        ),
        migrations.CreateModel(
            name='ReputationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_no_show', models.BooleanField(default=False)),
                ('is_complaint', models.BooleanField(default=False)),
                ('positive_tags', models.JSONField(blank=True, default=list)),
                ('comment', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('hidden_reason', models.TextField(blank=True)),
                ('hidden_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='substitutes.centercontact')),
                ('hidden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('phone_identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputation_records', to='substitutes.phoneidentity')),
                ('posting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reputation_records', to='substitutes.posting')),
            ],
            options={
                'verbose_name': '평판 기록',
                'verbose_name_plural': '평판 기록',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['phone_identity', 'occurred_at'], name='sub_reputation_phone_idx')],
            },
        ),
    ]
