# Generated by Django 6.1.1 on 2026-09-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitutes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centercontact',
            name='password_hash',
            field=models.CharField(default='', editable=False, max_length=128),
        ),
        migrations.AddField(
            model_name='phoneidentity',
            name='password_hash',
            field=models.CharField(default='', editable=False, max_length=128),
        ),
    ]
