# Generated by Django 6.1.1 on 2026-09-11 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_type', models.CharField(choices=[('auto', '자동 감지'), ('qualification', '지도자 자격 취득 현황'), ('program', '기관·운영 프로그램 현황'), ('application', '프로그램 신청 현황')], max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('temporary_file', models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/')),
                ('sheet_name', models.CharField(blank=True, max_length=200)),
                ('encoding', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('preview', '미리보기'), ('validated', '검증 완료'), ('completed', '저장 완료'), ('failed', '실패')], default='preview', max_length=20)),
                ('row_count', models.PositiveBigIntegerField(default=0)),
                ('success_count', models.PositiveBigIntegerField(default=0)),
                ('failure_count', models.PositiveBigIntegerField(default=0)),
                ('duplicate_count', models.PositiveBigIntegerField(default=0)),
                ('columns', models.JSONField(blank=True, default=list)),
                ('missing_counts', models.JSONField(blank=True, default=dict)),
                ('preview_rows', models.JSONField(blank=True, default=list)),
                ('field_mapping', models.JSONField(blank=True, default=dict)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '업로드 이력',
                'verbose_name_plural': '업로드 이력',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('normalized_name', models.CharField(db_index=True, max_length=300)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('normalized_region', models.CharField(blank=True, db_index=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('institution_type', models.CharField(blank=True, max_length=100)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': '기관',
                'verbose_name_plural': '기관',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('normalized_name', 'normalized_region'), name='unique_institution_region')],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=400)),
                ('normalized_name', models.CharField(db_index=True, max_length=400)),
                ('sport', models.CharField(blank=True, max_length=150)),
                ('normalized_sport', models.CharField(blank=True, db_index=True, max_length=150)),
                ('target', models.CharField(blank=True, max_length=300)),
                ('weekdays', models.CharField(blank=True, max_length=100)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='운영', max_length=50)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='app.institution')),
            ],
            options={
                'verbose_name': '운영 프로그램',
                'verbose_name_plural': '운영 프로그램',
                'ordering': ['institution__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=64, unique=True)),
                ('reference_date', models.DateField(blank=True, null=True)),
                ('recruitment_year', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('applicants', models.PositiveIntegerField(blank=True, null=True)),
                ('waitlist', models.PositiveIntegerField(blank=True, null=True)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='app.program')),
            ],
            options={
                'verbose_name': '프로그램 신청 현황',
                'verbose_name_plural': '프로그램 신청 현황',
                'ordering': ['-reference_date', 'program__name'],
            },
        ),
        migrations.CreateModel(
            name='QualificationAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_year', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('normalized_region', models.CharField(blank=True, db_index=True, max_length=100)),
                ('sport', models.CharField(blank=True, max_length=150)),
                ('normalized_sport', models.CharField(blank=True, db_index=True, max_length=150)),
                ('qualification_type', models.CharField(blank=True, max_length=200)),
                ('grade', models.CharField(blank=True, max_length=100)),
                ('acquisition_count', models.PositiveIntegerField(default=0)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': '지도자 자격 취득 현황',
                'verbose_name_plural': '지도자 자격 취득 현황',
                'ordering': ['-acquisition_year', 'normalized_sport'],
                'constraints': [models.UniqueConstraint(fields=('acquisition_year', 'normalized_region', 'normalized_sport', 'qualification_type', 'grade', 'source_filename'), name='unique_qualification_aggregate')],
            },
        ),
    ]
