# Generated by Django 6.1.1 on 2026-09-11 05:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstatus',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='is_synthetic',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name='applicationstatus',
            constraint=models.UniqueConstraint(fields=('program', 'reference_date'), name='unique_program_application_period'),
        ),
    ]
