# Generated by Django 6.1.1 on 2026-09-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_applicationstatus_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstatus',
            name='is_synthetic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='applicationstatus',
            index=models.Index(fields=['is_synthetic', 'reference_date'], name='app_demo_period_idx'),
        ),
    ]
