# Generated by Django 6.1.1 on 2026-09-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_programcleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_code', models.CharField(db_index=True, max_length=10)),
                ('grade_name', models.CharField(max_length=100)),
                ('phase', models.CharField(max_length=30)),
                ('season', models.CharField(blank=True, max_length=30)),
                ('course_type', models.CharField(blank=True, max_length=30)),
                ('milestone', models.CharField(max_length=50)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('raw_text', models.CharField(blank=True, max_length=200)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '연간일정계획 캐시',
                'verbose_name_plural': '연간일정계획 캐시',
                'ordering': ['grade_code', 'phase', 'season', 'course_type'],
            },
        ),
        migrations.CreateModel(
            name='ExamScheduleFetchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_code', models.CharField(max_length=10, unique=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '연간일정계획 갱신 상태',
                'verbose_name_plural': '연간일정계획 갱신 상태',
            },
        ),
    ]
