# Generated by Django 5.2.17 on 2026-09-16 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_examschedule_examschedulefetchstatus'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='programcleanup',
            name='app_cleanup_usage_idx',
        ),
        migrations.RemoveField(
            model_name='applicationstatus',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='applicationstatus',
            name='recruitment_year',
        ),
        migrations.RemoveField(
            model_name='applicationstatus',
            name='source_filename',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='source_filename',
        ),
        migrations.RemoveField(
            model_name='program',
            name='match_updated_at',
        ),
        migrations.RemoveField(
            model_name='programcleanup',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='programcleanup',
            name='updated_at',
        ),
        migrations.RunSQL(
            sql=[
                "UPDATE app_program SET source_key = substr(source_key, 1, 32)",
                "UPDATE app_applicationstatus SET source_key = substr(source_key, 1, 32)",
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='applicationstatus',
            name='source_key',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='source_key',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='programcleanup',
            name='reference_date',
            field=models.DateField(),
        ),
    ]
