# Generated by Django 5.2.17 on 2026-09-16 01:28

import hashlib
import json

import django.db.models.deletion
from django.db import migrations, models


def _key(value):
    return hashlib.sha256(value.encode('utf-8')).hexdigest()[:32]


def normalize_repeated_values(apps, schema_editor):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        sources = cursor.execute(
            "SELECT DISTINCT source_filename FROM app_program WHERE source_filename <> ''"
        ).fetchall()
        cursor.executemany(
            'INSERT INTO app_datasource (filename) VALUES (%s)', sources,
        )
        cursor.execute('''
            UPDATE app_program
               SET source_id = (
                   SELECT id FROM app_datasource
                    WHERE filename = app_program.source_filename
               )
        ''')

        payload_rows = cursor.execute(
            'SELECT DISTINCT match_rules, match_candidates FROM app_program'
        ).fetchall()
        payloads = []
        for rules_text, candidates_text in payload_rows:
            rules = json.loads(rules_text or '[]')
            candidates = json.loads(candidates_text or '[]')
            canonical = json.dumps(
                {'rules': rules, 'candidates': candidates},
                ensure_ascii=False, sort_keys=True, separators=(',', ':'),
            )
            payloads.append((_key(canonical), rules_text or '[]', candidates_text or '[]'))
        cursor.executemany(
            'INSERT INTO app_programmatchpayload (payload_key, rules, candidates) VALUES (%s, %s, %s)',
            payloads,
        )
        cursor.execute(
            'CREATE INDEX app_tmp_match_payload_lookup '
            'ON app_programmatchpayload (rules, candidates)'
        )
        cursor.execute('''
            UPDATE app_program
               SET match_payload_id = (
                   SELECT id FROM app_programmatchpayload
                    WHERE rules = app_program.match_rules
                      AND candidates = app_program.match_candidates
                    LIMIT 1
               )
        ''')
        cursor.execute('DROP INDEX app_tmp_match_payload_lookup')

        detail_rows = cursor.execute(
            'SELECT DISTINCT evidence, rules FROM app_programcleanup'
        ).fetchall()
        details = []
        for evidence, rules_text in detail_rows:
            rules = json.loads(rules_text or '[]')
            canonical = json.dumps(
                {'evidence': evidence or '', 'rules': rules},
                ensure_ascii=False, sort_keys=True, separators=(',', ':'),
            )
            details.append((_key(canonical), evidence or '', rules_text or '[]'))
        cursor.executemany(
            'INSERT INTO app_programcleanupdetail (detail_key, evidence, rules) VALUES (%s, %s, %s)',
            details,
        )
        cursor.execute(
            'CREATE INDEX app_tmp_cleanup_detail_lookup '
            'ON app_programcleanupdetail (evidence, rules)'
        )
        cursor.execute('''
            UPDATE app_programcleanup
               SET detail_id = (
                   SELECT id FROM app_programcleanupdetail
                    WHERE evidence = app_programcleanup.evidence
                      AND rules = app_programcleanup.rules
                    LIMIT 1
               )
        ''')
        cursor.execute('DROP INDEX app_tmp_cleanup_detail_lookup')


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_programcleanup_app_cleanup_usage_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': '데이터 출처',
                'verbose_name_plural': '데이터 출처',
                'ordering': ['filename'],
            },
        ),
        migrations.CreateModel(
            name='ProgramCleanupDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_key', models.CharField(max_length=32, unique=True)),
                ('evidence', models.TextField(blank=True)),
                ('rules', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': '프로그램 정리 상세',
                'verbose_name_plural': '프로그램 정리 상세',
            },
        ),
        migrations.CreateModel(
            name='ProgramMatchPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload_key', models.CharField(max_length=32, unique=True)),
                ('rules', models.JSONField(blank=True, default=list)),
                ('candidates', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': '프로그램 매칭 상세',
                'verbose_name_plural': '프로그램 매칭 상세',
            },
        ),
        migrations.AddField(
            model_name='program',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='app.datasource'),
        ),
        migrations.AddField(
            model_name='programcleanup',
            name='detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cleanups', to='app.programcleanupdetail'),
        ),
        migrations.AddField(
            model_name='program',
            name='match_payload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='app.programmatchpayload'),
        ),
        migrations.RunPython(normalize_repeated_values, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='program',
            name='match_candidates',
        ),
        migrations.RemoveField(
            model_name='program',
            name='match_rules',
        ),
        migrations.RemoveField(
            model_name='program',
            name='source_filename',
        ),
        migrations.RemoveField(
            model_name='programcleanup',
            name='evidence',
        ),
        migrations.RemoveField(
            model_name='programcleanup',
            name='rules',
        ),
    ]
