# Generated by Django 5.2.17 on 2026-09-16 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_datasource_programcleanupdetail_programmatchpayload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstatus',
            name='program',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='app.program'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='normalized_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='program',
            name='match_is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='programcleanup',
            name='matched_sport',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaned_programs', to='app.canonicalsport'),
        ),
        migrations.AlterField(
            model_name='qualificationaggregate',
            name='acquisition_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
